services:
  - type: web
    name: mango-leaf-disease-detection
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /
